In [1]:
%config InlineBackend.figure_formats = ['svg']

# 第二章 感知机

## 感知机的实现

In [2]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1 * w1 + x2 * w2
    if tmp <= theta:
        return 0
    else:
        return 1

In [3]:
[
    AND(0, 0),  # 输出0
    AND(1, 0),  # 输出0
    AND(0, 1),  # 输出0
    AND(1, 1),  # 输出1
]

[0, 0, 0, 1]

In [4]:
import numpy as np

In [5]:
x = np.array([0, 1]) # 输入
x

array([0, 1])

In [6]:
w = np.array([0.5, 0.5]) # 权重
w

array([0.5, 0.5])

In [7]:
b = -0.7 # 偏置

In [8]:
w * x

array([0. , 0.5])

In [9]:
np.sum(w * x)

0.5

In [10]:
np.sum(w * x) + b

-0.19999999999999996

In [11]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7

    tmp = np.sum(x * w) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [12]:
[
    AND(0, 0),  # 输出0
    AND(1, 0),  # 输出0
    AND(0, 1),  # 输出0
    AND(1, 1),  # 输出1
]

[0, 0, 0, 1]

In [13]:
def NAND(x1, x2): # 与非门
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])  # 仅权重和偏置与AND不同！
    b = 0.7
    tmp = np.sum(w * x) + b
    if tmp <= 0:
        return 0
    else:
        return 1


In [14]:
[
    NAND(0, 0),  # 输出1
    NAND(1, 0),  # 输出1
    NAND(0, 1),  # 输出1
    NAND(1, 1),  # 输出0
]

[1, 1, 1, 0]

In [15]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])  # 仅权重和偏置与AND不同！
    b = -0.2
    tmp = np.sum(w * x) + b
    if tmp <= 0:
        return 0
    else:
        return 1


In [16]:
[
    OR(0, 0),  # 输出0
    OR(1, 0),  # 输出1
    OR(0, 1),  # 输出1
    OR(1, 1),  # 输出1
]

[0, 1, 1, 1]

## 感知机的局限性

无法线性区分异或门

## 多层感知机

In [17]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [18]:
[
    XOR(0, 0),  # 输出0
    XOR(1, 0),  # 输出1
    XOR(0, 1),  # 输出1
    XOR(1, 1),  # 输出0
]

[0, 1, 1, 0]